include_guard(GLOBAL)
# App-private rasterization; engine/headless targets never acquire font dependencies.
include(FetchContent)
set(FT_DISABLE_ZLIB ON CACHE BOOL "" FORCE)
set(FT_DISABLE_BZIP2 ON CACHE BOOL "" FORCE)
set(FT_DISABLE_PNG ON CACHE BOOL "" FORCE)
set(FT_DISABLE_HARFBUZZ ON CACHE BOOL "" FORCE)
set(FT_DISABLE_BROTLI ON CACHE BOOL "" FORCE)
set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
FetchContent_Declare(freetype
    URL https://codeload.github.com/freetype/freetype/tar.gz/refs/tags/VER-2-13-3
    URL_HASH SHA256=bc5c898e4756d373e0d991bab053036c5eb2aa7c0d5c67e8662ddc6da40c4103
    TLS_VERIFY TRUE DOWNLOAD_EXTRACT_TIMESTAMP FALSE SYSTEM EXCLUDE_FROM_ALL)
FetchContent_MakeAvailable(freetype)
set(_font_base https://raw.githubusercontent.com/notofonts/noto-fonts/ffebf8c1ee449e544955a7e813c54f9b73848eac)
foreach(_asset font notice)
    if(_asset STREQUAL "font")
        set(_url "${_font_base}/hinted/ttf/NotoSans/NotoSans-Regular.ttf")
        set(_name NotoSans-Regular.ttf)
        set(_sha b85c38ecea8a7cfb39c24e395a4007474fa5a4fc864f6ee33309eb4948d232d5)
    else()
        set(_url "${_font_base}/LICENSE")
        set(_name NOTO-LICENSE.txt)
        set(_sha 0dab92d0544f7b233403f14b84a663bdbfa746982eda629e7f4f9ffe1b036feb)
    endif()
    set(_path "${CMAKE_CURRENT_BINARY_DIR}/${_name}")
    set(_existing "")
    if(EXISTS "${_path}")
        file(SHA256 "${_path}" _existing)
    endif()
    if(NOT _existing STREQUAL _sha)
        file(DOWNLOAD "${_url}" "${_path}" EXPECTED_HASH "SHA256=${_sha}" TLS_VERIFY ON)
    endif()
endforeach()
configure_file("${freetype_SOURCE_DIR}/docs/FTL.TXT" "${CMAKE_CURRENT_BINARY_DIR}/FREETYPE-LICENSE.txt" COPYONLY)
configure_file("${freetype_SOURCE_DIR}/LICENSE.TXT" "${CMAKE_CURRENT_BINARY_DIR}/FREETYPE-LICENSE-OPTIONS.txt" COPYONLY)
