include_guard(GLOBAL)

# Macro intentionally keeps enable_language in the caller's directory scope.
# Merely including this file does not enable C or acquire any dependency.
macro(opensim_setup_sdl)
    if(NOT TARGET SDL3::SDL3-static)
        enable_language(C)
        _opensim_acquire_sdl()
    endif()
endmacro()

function(_opensim_acquire_sdl)
    include(FetchContent)
    set(OPENSIM_SDL_SOURCE_DIR "" CACHE PATH "Explicit offline SDL 3.2.28 source; caller supplies provenance")
    set(OPENSIM_SDL_ARCHIVE "" CACHE FILEPATH "Optional SDL archive verified against the pinned SHA256")
    if(OPENSIM_SDL_SOURCE_DIR AND OPENSIM_SDL_ARCHIVE)
        message(FATAL_ERROR "Choose SDL source directory or archive, not both")
    endif()
    if(FETCHCONTENT_SOURCE_DIR_SDL3)
        message(FATAL_ERROR "Use the validated OPENSIM_SDL_SOURCE_DIR override")
    endif()
    set(SDL_SHARED OFF CACHE BOOL "" FORCE)
    set(SDL_STATIC ON CACHE BOOL "" FORCE)
    set(SDL_TEST_LIBRARY OFF CACHE BOOL "" FORCE)
    set(SDL_TESTS OFF CACHE BOOL "" FORCE)
    set(SDL_EXAMPLES OFF CACHE BOOL "" FORCE)
    # Upstream 3.2.28 define_sdl_subsystem options; demo needs video/render only.
    set(SDL_DIALOG ON CACHE BOOL "" FORCE)
    foreach(_subsystem AUDIO CAMERA JOYSTICK HAPTIC HIDAPI POWER SENSOR GPU)
        set(SDL_${_subsystem} OFF CACHE BOOL "" FORCE)
    endforeach()
    if(OPENSIM_SDL_SOURCE_DIR)
        cmake_path(ABSOLUTE_PATH OPENSIM_SDL_SOURCE_DIR NORMALIZE OUTPUT_VARIABLE _source)
        if(NOT EXISTS "${_source}/include/SDL3/SDL_version.h" OR
           NOT EXISTS "${_source}/LICENSE.txt" OR NOT EXISTS "${_source}/CMakeLists.txt")
            message(FATAL_ERROR "SDL source requires version header, CMakeLists.txt and LICENSE.txt")
        endif()
        file(READ "${_source}/include/SDL3/SDL_version.h" _version)
        foreach(_pair MAJOR=3 MINOR=2 MICRO=28)
            string(REPLACE "=" ";" _parts "${_pair}")
            list(GET _parts 0 _part)
            list(GET _parts 1 _value)
            if(NOT _version MATCHES "#define[ \t]+SDL_${_part}_VERSION[ \t]+${_value}([ \t\r\n]|$)")
                message(FATAL_ERROR "Offline source must be SDL 3.2.28 (${_part} mismatch)")
            endif()
        endforeach()
        message(STATUS "SDL explicit source override: ${_source}; caller supplies provenance")
        FetchContent_Declare(SDL3 SOURCE_DIR "${_source}" SYSTEM EXCLUDE_FROM_ALL)
    else()
        set(_url "https://codeload.github.com/libsdl-org/SDL/tar.gz/refs/tags/release-3.2.28")
        if(OPENSIM_SDL_ARCHIVE)
            cmake_path(ABSOLUTE_PATH OPENSIM_SDL_ARCHIVE NORMALIZE OUTPUT_VARIABLE _url)
            if(NOT EXISTS "${_url}")
                message(FATAL_ERROR "SDL archive does not exist")
            endif()
            file(SHA256 "${_url}" _hash)
            if(NOT _hash STREQUAL "5c908f07a93087037d3319bc5d820ba8df14ac98bdbdf24af9084ef460ce01b1")
                message(FATAL_ERROR "SDL archive SHA256 mismatch")
            endif()
        endif()
        FetchContent_Declare(SDL3 URL "${_url}"
            URL_HASH SHA256=5c908f07a93087037d3319bc5d820ba8df14ac98bdbdf24af9084ef460ce01b1
            TLS_VERIFY TRUE DOWNLOAD_EXTRACT_TIMESTAMP FALSE SYSTEM EXCLUDE_FROM_ALL)
    endif()
    FetchContent_MakeAvailable(SDL3)
    if(NOT TARGET SDL3::SDL3-static)
        message(FATAL_ERROR "SDL static target missing")
    endif()
    set(OPENSIM_SDL_LICENSE_FILE "${sdl3_SOURCE_DIR}/LICENSE.txt" PARENT_SCOPE)
endfunction()
