include_guard(GLOBAL)
macro(opensim_setup_mechanics)
    enable_language(C)
    include(FetchContent)
    set(BOX2D_SAMPLES OFF CACHE BOOL "" FORCE)
    set(BOX2D_UNIT_TESTS OFF CACHE BOOL "" FORCE)
    set(BOX2D_BENCHMARKS OFF CACHE BOOL "" FORCE)
    set(BOX2D_DOCS OFF CACHE BOOL "" FORCE)
    set(BOX2D_DISABLE_SIMD ON CACHE BOOL "" FORCE)
    set(QJS_ENABLE_INSTALL OFF CACHE BOOL "" FORCE)
    set(QJS_BUILD_LIBC OFF CACHE BOOL "" FORCE)
    set(QJS_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
    set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
    FetchContent_Declare(box2d URL https://codeload.github.com/erincatto/box2d/tar.gz/refs/tags/v3.1.1
        URL_HASH SHA256=fb6ef914b50f4312d7d921a600eabc12318bb3c55a0b8c0b90608fa4488ef2e4 TLS_VERIFY TRUE DOWNLOAD_EXTRACT_TIMESTAMP FALSE SYSTEM EXCLUDE_FROM_ALL)
    FetchContent_Declare(quickjs URL https://codeload.github.com/quickjs-ng/quickjs/tar.gz/refs/tags/v0.17.0
        URL_HASH SHA256=559bc4c420475e55c7ab4510adbc562f55d7524d75e8e89d79ce4bb02f5687d9 TLS_VERIFY TRUE DOWNLOAD_EXTRACT_TIMESTAMP FALSE SYSTEM EXCLUDE_FROM_ALL)
    FetchContent_MakeAvailable(box2d quickjs)
    set(OPENSIM_BOX2D_NOTICE "${box2d_SOURCE_DIR}/LICENSE" CACHE INTERNAL "Box2D license")
    set(OPENSIM_QUICKJS_NOTICE "${quickjs_SOURCE_DIR}/LICENSE" CACHE INTERNAL "QuickJS license")
endmacro()

# App-only decoder; no stdio or external-resource loading in source image decode.
if(OPENSIM_BUILD_APP)
    set(_stb_dir "${PROJECT_BINARY_DIR}/_deps/opensim-stb")
    file(MAKE_DIRECTORY "${_stb_dir}")
    foreach(_name stb_image.h LICENSE)
        if(_name STREQUAL "stb_image.h")
            set(_sha 594c2fe35d49488b4382dbfaec8f98366defca819d916ac95becf3e75f4200b3)
        else()
            set(_sha bebfe904b14301657e4e5d655c811d51fd31b97c455b9cc2d8600d6bac6cff63)
        endif()
        set(_existing "")
        if(EXISTS "${_stb_dir}/${_name}")
            file(SHA256 "${_stb_dir}/${_name}" _existing)
        endif()
        if(NOT _existing STREQUAL _sha)
            file(DOWNLOAD "https://raw.githubusercontent.com/nothings/stb/2c980bb59875b0d32144a71867fbdebb2f77cd20/${_name}"
                "${_stb_dir}/${_name}" EXPECTED_HASH "SHA256=${_sha}" TLS_VERIFY ON)
        endif()
    endforeach()
    set(OPENSIM_STB_DIR "${_stb_dir}" CACHE INTERNAL "Pinned image decoder")
endif()
