include_guard(GLOBAL)

function(opensim_configure_target target)
    get_target_property(_type "${target}" TYPE)
    if(_type STREQUAL "INTERFACE_LIBRARY")
        target_compile_features("${target}" INTERFACE cxx_std_20)
        return()
    endif()
    target_compile_features("${target}" PUBLIC cxx_std_20)
    set_target_properties("${target}" PROPERTIES CXX_EXTENSIONS OFF CXX_STANDARD_REQUIRED ON)
    if(MSVC)
        target_compile_options("${target}" PRIVATE /W4 /permissive- /utf-8 /EHsc)
        if(OPENSIM_WARNINGS_AS_ERRORS)
            target_compile_options("${target}" PRIVATE /WX)
        endif()
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
        target_compile_options("${target}" PRIVATE -Wall -Wextra -Wpedantic)
        if(OPENSIM_WARNINGS_AS_ERRORS)
            target_compile_options("${target}" PRIVATE -Werror)
        endif()
    endif()
endfunction()

function(opensim_add_module name)
    cmake_parse_arguments(PARSE_ARGV 1 ARG "" "" "SOURCES;HEADERS;PUBLIC_DEPS;PRIVATE_DEPS")
    if(ARG_UNPARSED_ARGUMENTS OR ARG_KEYWORDS_MISSING_VALUES)
        message(FATAL_ERROR "Invalid opensim_add_module arguments for ${name}")
    endif()
    # Direct internal edges from spec/architecture.md. Do not infer transitive permission.
    set(_known core math scene collision constraints physics renderer editor visualization
        analysis serialization compat platform app)
    set(_core "")
    set(_math "")
    set(_scene core math)
    set(_collision core math scene)
    set(_constraints core math scene)
    set(_physics core math scene collision constraints)
    set(_renderer core math scene)
    set(_editor core math scene)
    set(_visualization core math scene)
    set(_analysis core math scene)
    set(_serialization core math scene)
    set(_compat core math scene)
    set(_platform core)
    set(_app ${_known})
    list(REMOVE_ITEM _app app)
    if(NOT name IN_LIST _known)
        message(FATAL_ERROR "Unknown module: ${name}")
    endif()
    foreach(_dep IN LISTS ARG_PUBLIC_DEPS ARG_PRIVATE_DEPS)
        if(NOT _dep IN_LIST _${name})
            message(FATAL_ERROR "Forbidden internal dependency: ${name} -> ${_dep}")
        endif()
        if(NOT TARGET "opensim::${_dep}")
            message(FATAL_ERROR "Dependency is not registered: ${name} -> ${_dep}")
        endif()
    endforeach()
    if(NOT ARG_SOURCES AND NOT ARG_HEADERS)
        message(FATAL_ERROR "Module ${name} must list its sources or public headers explicitly")
    endif()
    if(ARG_SOURCES)
        add_library("opensim_${name}" STATIC ${ARG_SOURCES} ${ARG_HEADERS})
        set(_public PUBLIC)
        set(_private PRIVATE)
    else()
        if(ARG_PRIVATE_DEPS)
            message(FATAL_ERROR "Header-only module ${name} cannot hide private dependencies")
        endif()
        add_library("opensim_${name}" INTERFACE)
        target_sources("opensim_${name}" INTERFACE ${ARG_HEADERS})
        set(_public INTERFACE)
        set(_private INTERFACE)
    endif()
    add_library("opensim::${name}" ALIAS "opensim_${name}")
    target_include_directories("opensim_${name}" ${_public}
        "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>")
    foreach(_dep IN LISTS ARG_PUBLIC_DEPS)
        target_link_libraries("opensim_${name}" ${_public} "opensim::${_dep}")
    endforeach()
    foreach(_dep IN LISTS ARG_PRIVATE_DEPS)
        target_link_libraries("opensim_${name}" ${_private} "opensim::${_dep}")
    endforeach()
    opensim_configure_target("opensim_${name}")
endfunction()
